# Generated by Django 3.2.2 on 2021-06-05 03:31

import BestCarePharmacyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0002_medicine_medicine_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_img',
            field=models.ImageField(blank=True, null=True, upload_to=BestCarePharmacyApp.models.upload_path),
        ),
    ]
