# Generated by Django 3.2.2 on 2021-06-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0005_companyaccount_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
