# Generated by Django 3.2.2 on 2021-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0007_customerrequest_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
