# Generated by Django 3.2.2 on 2021-06-25 11:34

import BestCarePharmacyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0008_alter_employee_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to=BestCarePharmacyApp.models.upload_doctor_image)),
                ('degree', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField()),
            ],
        ),
    ]
