# Generated by Django 3.2.2 on 2021-06-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0009_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='degree',
            new_name='doctor_type',
        ),
    ]
