# Generated by Django 3.2.2 on 2021-08-20 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0014_auto_20210820_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 15, 18, 0, 671200)),
        ),
    ]
