# Generated by Django 3.2.2 on 2022-02-19 04:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0015_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 19, 10, 18, 9, 946017)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_id', to='BestCarePharmacyApp.medicine'),
        ),
    ]
