# Generated by Django 3.2.2 on 2022-04-23 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0016_auto_20220219_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 9, 56, 42, 913467)),
        ),
    ]
