# Generated by Django 3.2.2 on 2022-04-23 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestCarePharmacyApp', '0018_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 10, 0, 14, 633179)),
        ),
    ]
